title: Homebrew Formulae
description: Homebrew's package index

remote_theme: Homebrew/brew.sh

exclude:
  - bin
  - script
  - CNAME
  - LICENSE.txt
  - Rakefile
  - README.md
  - Gemfile*
  - vendor

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

permalink: :title

defaults:
  - scope:
      path: ""
    values:
      image: https://brew.sh/assets/img/homebrew-256x256.png
      search_name: Homebrew Formulae
      search_site: formulae

taps:
  core:
    repo: nodenv
    name: nodenv/nodenv
    fullname: nodenv/homebrew-nodenv
    remote: https://github.com/nodenv/homebrew-nodenv
  cask:
    repo: cask
    name: nodenv/cask
    fullname: nodenv/homebrew-cask
    remote: https://github.com/nodenv/homebrew-cask
  linux:
    repo: nodenv
    name: nodenv/nodenv
    fullname: nodenv/linuxbrew-nodenv
    remote: https://github.com/nodenv/linuxbrew-nodenv

logo: https://brew.sh/assets/img/homebrew-256x256.png

forkme_nwo: nodenv/formulae.brew.sh

# twitter:
#   username: MacHomebrew
