name: Re-gen Site Data
on:
  push: { branches: master }
  schedule: [{ cron: '0 9 * * *' }] # daily at 1am PST

jobs:
  generate:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile.lock') }}
      - run: brew tap nodenv/nodenv
      - run: bin/bundle install --deployment --jobs 4 --retry 3
      - run: bin/rake -m all_formulae data:analytics cask
      - uses: stefanzweifel/git-auto-commit-action@v4.1.1
        with:
          commit_message: 'regenerated all formula and analytics data'
