name: Test
on:
  push: { branches: master }
  pull_request: []

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-ruby@v1

    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile.lock') }}

    - name: Set up Homebrew
      run: |
        HOMEBREW_REPOSITORY="$HOME/Homebrew"
        export PATH="$HOMEBREW_REPOSITORY/bin:$PATH"
        rm -rf $HOMEBREW_REPOSITORY
        git clone --depth=1 https://github.com/Homebrew/brew "$HOMEBREW_REPOSITORY"
        HOMEBREW_CORE_TAP_DIR="$HOMEBREW_REPOSITORY/Library/Taps/homebrew/homebrew-core"
        mkdir -p "$HOMEBREW_CORE_TAP_DIR"
        rm -rf "$HOMEBREW_CORE_TAP_DIR"
        git clone --depth=1 https://github.com/Homebrew/homebrew-core "$HOMEBREW_CORE_TAP_DIR"
        NODENV_TAP_DIR="$HOMEBREW_REPOSITORY/Library/Taps/homebrew/homebrew-core"
        mkdir -p "$NODENV_TAP_DIR"
        rm -rf "$NODENV_TAP_DIR"
        git clone --depth=1 https://github.com/nodenv/homebrew-nodenv "$NODENV_TAP_DIR"
        export HOMEBREW_NO_ANALYTICS=1
        # trigger vendored ruby installation
        brew help

    - name: bundle install
      run: |
        gem install bundler -v "~>1"
        bundle install --deployment --binstubs --jobs 4 --retry 3

    - run: bin/rake build
