name: Test
on:
  push: { branches: master }
  pull_request: []

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile.lock') }}
    - uses: actions/setup-ruby@v1
    - uses: jasonkarns/setup-homebrew@master
      with: { taps: nodenv/nodenv }
    - name: bundle install
      run: |
        gem install bundler -v "~>1"
        bundle install --deployment --binstubs --jobs 4 --retry 3
    - run: bin/rake build
